### ISSUE TITLE
nie da się sciagnąc repozytorium 

### ISSUE THREAD

**Issue by krzysztof222** [kodiver/repository.kodiver#1]
jak sćiagnąc reposyterium <>

**Comment by gmaslowski** [comment]
http://kodiwpigulce.pl/jak-zainstalowac-wtyczke-leisure-streams-w-kodi-17-poradnik-kamery-na-zywo/

**Comment by gmaslowski** [comment]
https://kodiver.github.io/blog/2017/08/07/how-to-install-repository.html
